language: generic 
sudo: required
services:
  - docker: 

before_install:
  - docker build -t aemdock/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aemdock/docker-react npm run test
