version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /myspace/frontend/node_modules
      - /myspace/frontend /app
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /myspace/frontend/node_modules
      - /myspace/frontend /app
    command: ["npm", "run", "test"]
